### ISSUE TITLE
Adding exceptions to API calls

### ISSUE THREAD

**Issue by FabioFleitas** [sendwithus/sendwithus_python#42]
Right now you have to check the `status_code` of the response to see whether or not your API call went through and then read the `content` to see the error message. I'd like to suggest adding exceptions to the API calls instead. (This was inspired by how [sendgrid manages exceptions](https://github.com/sendgrid/sendgrid-python#error-handling))

Here's an example of some exceptions sendwithus could use:
```python
# exceptions.py

class SendwithusError(Exception):
    '''Base class for Sendwithus-related errors'''

class AuthenticationError(SendwithusError):
    pass

class APIError(SendwithusError):
    pass

class ServerError(SendwithusError):
    pass
```

And then adding a method to parse the response and raise appropriate exceptions:
```python
def _parse_response(self, response):
    if response.status_code == '403':
        raise AuthenticationError(response.content)
    ...
```

To keep backwards compatibility, we could also include a parameter in the API constructor such as `raise_exceptions=True` (similar to how Sendgrid does it).

Would love to hear your thoughts on this suggestion. I'd be happy to submit a pull request with accompanying test cases for this.

**Comment by FabioFleitas** [comment]
Let me know what you guys think, I'd be happy to submit a pull request for this.

**Comment by demoore** [comment]
Hey Fabio, that's a sweet idea — we're happy to take a look at a PR if you submit one! :smile:

**Comment by digismack** [comment]
+1

**Comment by bvanvugt** [comment]
@FabioFleitas awesome thanks - we'll take a look this week :)

**Comment by bvanvugt** [comment]
@FabioFleitas version 1.6.6 is available now :)
