### ISSUE TITLE
`file` class not available in Python3

### ISSUE THREAD

**Issue by m3nu** [sendwithus/sendwithus_python#47]
[This check](https://github.com/sendwithus/sendwithus_python/blob/master/sendwithus/__init__.py#L408) seems to fail in Python 3?
### Actual behaviour

```
  File "/usr/local/lib/python3.5/site-packages/mtools/mass_mailing.py", line 40, in from_excel
    inline=open(attachment, 'r')
  File "/usr/local/lib/python3.5/site-packages/sendwithus/__init__.py", line 408, in send
    if isinstance(inline, file):
NameError: name 'file' is not defined
```
### Steps to reproduce

Add `inline=open(attachment, 'r')` to `send`

**Comment by m3nu** [comment]
It should be `IOBase`, I [guess](http://stackoverflow.com/questions/18880948/python-3-3-2-check-that-object-is-of-type-file).

**Comment by m3nu** [comment]
Works when using `files` instead of `inline`. Is `inline` still used?

**Comment by demoore** [comment]
Yeah, an inlined attachment is [usually for embedded images](https://sendgrid.com/blog/embedding-images-emails-facts/). PR #46 should fix this 😸
