### ISSUE TITLE
email_id or template as the template_id field?

### ISSUE THREAD

**Issue by paddie** [sendwithus/sendwithus_python#52]
Looking at the csharp and the python clients, the fields `email_id` and `template` are used interchangeably. Is the python client behind, or are both fields valid as the `template_id` when sending an email?

**Comment by demoore** [comment]
They're interchangeable and we're moving toward's `template` for future clients. It's less confusing, there's a "Templates" section in the Sendwithus dashboard, not a "Emails" sections.
