### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by amureki** [sendwithus/sendwithus_python#67]
### Client version
4.1.0

### Expected behaviour
Readable and up-to-date change log file/release page reflecting latest changes.
Probably, we can go for single entry-point to not keep up to date both things.

### Actual behaviour
Neither change log file nor GitHub release page are up-to-date (version 5.0.0).

### Steps to reproduce
Go to repository and check 
https://github.com/sendwithus/sendwithus_python/blob/master/CHANGES.txt or 
https://github.com/sendwithus/sendwithus_python/releases

Thank you people for maintaining important package!

**Comment by demoore** [comment]
Thanks @amureki. That's a good point! I think we're going to drop the CHANGES.txt file and just keep the releases page updated.
